rules:
  color-no-hex: true
  #at-rule-blacklist: true
  #at-rule-empty-line-before: never
  #at-rule-name-case: true
  #at-rule-name-newline-after: true
  #at-rule-semicolon-space-before: true
  #at-rule-name-space-after: true
  #at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  #at-rule-semicolon-newline-after: true
  #at-rule-whitelist: true
  #block-closing-brace-empty-line-before: true
  #block-closing-brace-newline-after: true
  #block-closing-brace-newline-before: true
  #block-closing-brace-space-after: true
  #block-closing-brace-space-before: true
  #block-no-empty: true
  #block-opening-brace-newline-after: true
  #block-opening-brace-newline-before: true
  #block-opening-brace-space-after: true
  #block-opening-brace-space-before: true
  #color-hex-case: true
  #color-hex-length: true
  color-named:
    - always-where-possible
    - severity: warning
  #color-no-hex: true
  #color-no-invalid-hex: true
  #comment-empty-line-before: true
  #comment-no-empty: true
  #comment-whitespace-inside: true
  #comment-word-blacklist: true
  #custom-media-pattern: true
  #custom-property-empty-line-before: true
  #custom-property-pattern: true
  #declaration-bang-space-after: true
  #declaration-bang-space-before: true
  #declaration-block-no-duplicate-properties: true
  #declaration-block-no-redundant-longhand-properties: true
  #declaration-block-no-shorthand-property-overrides: true
  #declaration-block-semicolon-newline-after: true
  #declaration-block-semicolon-newline-before: true
  #declaration-block-semicolon-space-after: true
  #declaration-block-semicolon-space-before: true
  #declaration-block-single-line-max-declarations: true
  #declaration-block-trailing-semicolon: true
  #declaration-colon-newline-after: true
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  #declaration-empty-line-before: true
  declaration-no-important: true
  #declaration-property-unit-blacklist: true
  #declaration-property-unit-whitelist: true
  #declaration-property-value-blacklist: true
  #declaration-property-value-whitelist: true
  #font-family-no-missing-generic-family-keyword: true
  font-family-name-quotes: always-unless-keyword
  #font-family-no-duplicate-names: true
  font-weight-notation:
    - numeric
    - severity: warning
  #function-blacklist: true
  #function-calc-no-unspaced-operator: true
  #function-comma-newline-after: true
  #function-comma-newline-before: true
  #function-comma-space-after: true
  #function-comma-space-before: true
  #function-linear-gradient-no-nonstandard-direction: true
  #function-max-empty-lines: true
  #function-name-case: true
  #function-parentheses-newline-inside: true
  #function-parentheses-space-inside: true
  #function-url-no-scheme-relative: true
  function-url-quotes: always
  #function-url-scheme-blacklist: true
  #function-url-scheme-whitelist: true
  #function-whitelist: true
  #function-whitespace-after: true
  #keyframe-declaration-no-important: true
  #keyframes-name-pattern: true
  #length-zero-no-unit: true
  #linebreaks: true
  #max-empty-lines: true
  #max-line-length: true
  #max-nesting-depth: true
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  #media-feature-name-blacklist: true
  #media-feature-name-case: true
  #media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  #media-feature-name-value-whitelist: true
  #media-feature-name-whitelist: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  #media-query-list-comma-newline-after: true
  #media-query-list-comma-newline-before: true
  #media-query-list-comma-space-after: true
  #media-query-list-comma-space-before: true
  #no-descending-specificity: true
  #no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  #no-empty-source: true
  #no-empty-first-line: true
  #no-eol-whitespace: true
  #no-extra-semicolons: true
  #no-invalid-double-slash-comments: true
  #no-missing-end-of-source-newline: true
  #no-unknown-animations: true
  #number-leading-zero: true
  #number-max-precision: true
  #number-no-trailing-zeros: true
  #property-blacklist: true
  #property-case: true
  #property-no-unknown: true
  #property-no-vendor-prefix: true
  #property-whitelist: true
  #rule-empty-line-before: true
  selector-attribute-brackets-space-inside: never
  #selector-attribute-operator-blacklist: true
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  #selector-attribute-operator-whitelist: true
  #selector-attribute-quotes: true
  #selector-class-pattern: true
  #selector-combinator-blacklist: true
  selector-combinator-space-after: always
  #selector-combinator-space-before: true
  #selector-combinator-whitelist: true
  #selector-descendant-combinator-no-non-space: true
  #selector-id-pattern: true
  #selector-list-comma-newline-after: true
  #selector-list-comma-newline-before: true
  #selector-list-comma-space-after: true
  #selector-list-comma-space-before: true
  #selector-max-attribute: true
  #selector-max-class: true
  #selector-max-combinators: true
  #selector-max-compound-selectors: true
  #selector-max-empty-lines: true
  selector-max-id: 0
  #selector-max-pseudo-class: true
  #selector-max-specificity: true
  #selector-max-type: 0
  #selector-max-universal: true
  #selector-nested-pattern: true
  #selector-no-qualifying-type: true
  selector-no-vendor-prefix: true
  #selector-pseudo-class-blacklist: true
  #selector-pseudo-class-case: true
  #selector-pseudo-class-no-unknown: true
  #selector-pseudo-class-parentheses-space-inside: true
  #selector-pseudo-class-whitelist: true
  #selector-pseudo-element-blacklist: true
  #selector-pseudo-element-case: true
  selector-pseudo-element-colon-notation: double
  #selector-pseudo-element-no-unknown: true
  #selector-pseudo-element-whitelist: true
  #selector-type-case: true
  #selector-type-no-unknown: true
  #shorthand-property-no-redundant-values: true
  #string-no-newline: true
  string-quotes: single
  #time-min-milliseconds: true
  #unit-blacklist: true
  #unit-case: true
  #unit-no-unknown: true
  #unit-whitelist: true
  #value-keyword-case: true
  #value-list-comma-newline-after: true
  #value-list-comma-newline-before: true
  #value-list-comma-space-after: true
  #value-list-comma-space-before: true
  #value-list-max-empty-lines: true
  value-no-vendor-prefix: true
  indentation: tab
